repos:
  - repo: local
    hooks:
      - id: run-lint-exec
        name: Run lint-exec
        entry: poetry run task lint-exec
        language: system
        files: \.(py)$
        stages: [commit]
